name: Deploy to 2 VMs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key for VM 1
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_VM1 }}

      - name: Deploy to VM 1
        run: |
          ssh `nitiesh@52.183.142.13 "cd /path/to/app && ./deploy.sh"

      - name: Install SSH key for VM 2
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_VM2 }}

      - name: Deploy to VM 2
        run: |
          ssh nitiesh@52.183.139.178 "cd /path/to/app && ./deploy.sh"
